### ISSUE TITLE
Katex font missing

### ISSUE THREAD

**Issue by maple3142** [next-theme/plugins#34]
![image](https://user-images.githubusercontent.com/9370547/98959655-75d49c00-253e-11eb-8e32-a2e7055ccb61.png)

看起來是 `_vendors.yml` 裡面的 katex 沒有包含到 `katex/dist/fonts` 的原因

`_config.next.yml`:

```yml
rss: /atom.xml
footer:
    since: 2017
    icon:
        name: fa fa-user
        animated: false
        color: "#808080"
    copyright: null
    powered: false
    theme:
        enable: false
        version: false
favicon:
    small: /favicon.ico
    medium: /favicon.ico
    apple_touch_icon: /favicon.ico
    safari_pinned_tab: /favicon.ico
canonical: true
menu:
    home: / || fas fa-home
    about: /about/ || fas fa-user
    tags: /tags/ || fas fa-tags
    categories: /categories/ || fas fa-th
    archives: /archives/ || fas fa-archive
back2top:
    enable: true
    sidebar: false
    scrollpercent: true
scheme: Pisces
darkmode: true
social:
    GitHub: //github.com/maple3142 || fab fa-github
    E-Mail: mailto:kirby741852963@gmail.com || fa fa-envelope
    Twitter: //twitter.com/maple3142 || fab fa-twitter
    Telegram: //t.me/maple3142 || fab fa-telegram
    RSS: /atom.xml || fas fa-rss
social_icons:
    enable: true
    icons_only: true
avatar:
    url: /img/maple3142.jpg
font:
    enable: true
    global:
        external: false
        family: Arial
        size:
    codes:
        external: false
        family: monospace
math:
    katex:
        enable: true
disqus:
    enable: true
    shortname: maple3142
    count: false
comments:
    lazyload: true
google_site_verification: ebMkYF0f5RX6bDiatwVeIUTBEfOrg886kYf_tk_gnS4
local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
    unescape: false
    preload: false
motion:
    enable: false
vendors:
    internal: local
    plugins: local
#vendors:
    # fontawesome: /fa-lite/style.css #//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css
    # mediumzoom: //cdnjs.cloudflare.com/ajax/libs/medium-zoom/1.0.6/medium-zoom.min.js
    # anime: //cdnjs.cloudflare.com/ajax/libs/animejs/3.2.0/anime.min.js
related_posts:
    enable: true
custom_file_path:
    head: source/_data/head.njk
codeblock:
    theme:
        light: atom-one-light
        dark: monokai-sublime
    copy_button:
        enable: true
        style: flat
post_meta:
    item_text: true
    created_at: true
    updated_at:
        enable: false
    categories: true
scroll_to_more: false
reading_progress:
    enable: true
    color: "#37c6c0"
    height: 2px
# I use my own implementation
google_analytics:
    tracking_id: UA-108821694-2
    only_pageview: true
mediumzoom: true
text_align:
    desktop: left
    mobile: left

```

`package.json`:

```json
{
	"name": "maple-blog",
	"version": "0.0.0",
	"private": true,
	"scripts": {
		"dev": "hexo s",
		"build": "hexo g && gulp",
		"prod": "hexo g && gulp prod",
		"serve": "httpsrv -i -f 404.html"
	},
	"dependencies": {
		"@next-theme/plugins": "^8.0.2",
		"graceful-fs": "^4.2.2",
		"gulp": "^4.0.2",
		"gulp-csso": "^4.0.1",
		"gulp-dom": "^1.0.0",
		"gulp-htmlclean": "^2.7.22",
		"gulp-htmlmin": "^5.0.1",
		"gulp-imagemin": "^7.1.0",
		"gulp-pretty-data": "^0.2.0",
		"gulp-terser": "^1.2.0",
		"hexo": "^5.1.1",
		"hexo-fs": "^3.1.0",
		"hexo-generator-archive": "^1.0.0",
		"hexo-generator-category": "^1.0.0",
		"hexo-generator-feed": "^3.0.0",
		"hexo-generator-index": "^2.0.0",
		"hexo-generator-restful": "^0.2.3",
		"hexo-generator-robotstxt": "^0.2.0",
		"hexo-generator-search": "^2.4.0",
		"hexo-generator-sitemap": "^2.0.0",
		"hexo-generator-tag": "^1.0.0",
		"hexo-related-popular-posts": "^5.0.0",
		"hexo-renderer-ejs": "^1.0.0",
		"hexo-renderer-markdown-it-plus": "^1.0.4",
		"hexo-renderer-stylus": "^2.0.0",
		"hexo-server": "^2.0.0",
		"hexo-util": "^2.4.0",
		"jsdom": "^16.4.0",
		"minimatch": "^3.0.4",
		"nunjucks": "^3.2.0"
	},
	"hexo": {
		"version": "5.1.1"
	},
	"devDependencies": {
		"httpsrv": "^0.3.2"
	}
}
```
