### ISSUE TITLE
Cannot find module 'firebase/package.json'

### ISSUE THREAD

**Issue by aixiu** [next-theme/plugins#8]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/next-theme/hexo-theme-next/releases/latest) version of NexT.
- [x] I have already read the relevant documents of [Hexo](https://hexo.io/docs/) and [NexT](https://theme-next.js.org/docs/).
- [x] I have already searched for current [issues](https://github.com/next-theme/hexo-theme-next/issues), which does not help me.

***

## Other Information 
未启用firebase插件。
```yml
# Another tool to show number of visitors to each article.
# Visit https://console.firebase.google.com/u/0/ to get apiKey and projectId.
# Visit https://firebase.google.com/docs/firestore/ to get more information about firestore.
firestore:
  enable: false
  collection: articles # Required, a string collection name to access firestore database
  apiKey: # Required
  projectId: # Required

...and

  # Firebase
  firebase_app:
  firebase_firestore:
```

```yml
INFO  Start processing
Cannot find module 'firebase/package.json'
Require stack:
- E:\Blog\node_modules\@next-theme\plugins\index.js
- E:\Blog\themes\next\scripts\events\lib\vendors.js
Cannot find module 'firebase/package.json'
Require stack:
- E:\Blog\node_modules\@next-theme\plugins\index.js
- E:\Blog\themes\next\scripts\events\lib\vendors.js
```

### Node.js and NPM Information

```
$ node -v && npm -v
v12.16.1
6.13.4
```

所有的插件版本。
```yml
$ npm ls --depth 0
hexo-site@0.0.0 E:\My_blog
+-- @next-theme/plugins@0.1.0
+-- hexo@5.0.2
+-- hexo-abbrlink@2.2.1
+-- hexo-baidu-url-submit@0.0.6
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.9
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-searchdb@1.3.2
+-- hexo-generator-sitemap@2.1.0
+-- hexo-generator-tag@1.0.0
+-- hexo-next-tag@0.3.0 (github:theme-next/hexo-next-tag#095ca82d63db8e6e5231fa9a811d3d68f3d8cc88)
+-- hexo-next-utteranc@1.0.0 (github:theme-next/hexo-next-utteranc#f592272a73cb47923f25443709786942f0398a69)
+-- hexo-related-popular-posts@5.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@2.0.0
+-- hexo-util@2.3.0
+-- hexo-word-counter@0.0.2
`-- shelljs@0.8.4
```
卸载@next-theme/plugins@0.1.0插件，正常。
